def menuContactos():
    print("-------------------------")
    print("Salir 0:")
    print("Opcion 1: Añadir contacto")
    print("Opcion 2: Buscar contacto")
    print("Opcion 3: Ver contactos")
    print("-------------------------")
    return int(input("Opcion: "))

def menuAlgoritmia():
    print("---------------------------------")
    print("Salir 0:")
    print("Opcion 1: Conversor temperaturas")
    print("Opcion 2: Numeros pares/impares")
    print("Opcion 3: Frecuencia de caracteres")
    print("Opcion 4: Calculadora básica")
    print("Opcion 5: Ordenación de palabras")
    print("Opcion 6: Números primos en un rango")
    print("Opcion 7: Gestión de notas")
    print("Opcion 8: Juego de adivinanza")
    print("---------------------------------")
    return int(input("Opcion: "))

def menuSecuencias():
    print("------------------------------------------------")
    print("Salir 0:")
    print("Opcion 1: Diccionario de frecuencias de palabras")
    print("Opcion 2: Tuplas y coordenadas")
    print("Opcion 3: Diccionario inverso")
    print("Opcion 4: Lista de diccionarios (agenda)")
    print("------------------------------------------------")
    return int(input("Opcion: "))